/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pinguinoconpulgares (https://sketchfab.com/pinguinoconpulgares)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/badass-exosuit-5a94afcec4f44467b509b2d6a7c93ea6
title: Badass exosuit
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Robot(props) {
  const { nodes, materials } = useGLTF("/robot/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-2, 6, -2.5]} scale={50}>
          {/* <mesh geometry={nodes.Plane_1.geometry} material={materials.WHITE} /> */}
          <mesh geometry={nodes.Plane_2.geometry} material={materials.BODY} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials.LEG_L} />
          <mesh geometry={nodes.Plane_4.geometry} material={materials.LEG_R} />
          <mesh
            geometry={nodes.Plane_5.geometry}
            material={materials.material}
          />
          <mesh geometry={nodes.Plane_6.geometry} material={materials.ARM_L} />
          <mesh geometry={nodes.Plane_7.geometry} material={materials.ARM_R} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robot/scene.gltf");
